root: true
env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style

parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'
  - jest

rules:
  '@typescript-eslint/explicit-module-boundary-types': 'off'
